# Generated by Django 3.2 on 2021-04-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='c_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='contact',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pass2word',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
