# Generated by Django 3.2 on 2021-04-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_auto_20210427_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='lname',
        ),
    ]
