# Generated by Django 3.2 on 2021-04-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20210413_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.ImageField(upload_to='')),
                ('pass2word', models.CharField(max_length=500)),
                ('c_password', models.CharField(max_length=500)),
            ],
        ),
    ]
