# Generated by Django 3.2 on 2021-05-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0022_auto_20210515_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
